### ISSUE TITLE
Prevent rendering forms you're not allwoed to fill

### ISSUE THREAD

**Issue by n1k0** [Kinto/kinto-admin#131]
#### Todo

- [x] Check permission when editing a bucket (#134) 
- [x] Check permission when editing a collection 
- [x] Check permission when editing a record 

#### The issue

![](http://i.imgur.com/cehJ6tr.png)

This is super frustrating :)

**Comment by Natim** [comment]
If you have the read permission you should be able to display them.
However the submit button should be missing and the fields readonly.

**Comment by n1k0** [comment]
Yes indeed. That plus a clear warning at the top and we're good to go.

**Comment by n1k0** [comment]
Fixed by 135.
