### ISSUE TITLE
Allow creating schemaless collections

### ISSUE THREAD

**Issue by n1k0** [Kinto/kinto-admin#150]
Right now we enforce creating a schema and add display fields into all created collection metas. We should relax this rule and allow people to simply create schemaless collections.
#### Todo
- [ ] Ensure a schemaless collection can be listed
- [ ] Ensure we can add records to a schemaless collection (raw JSON editor)
- [ ] Ensure we can bulk add records to a schemaless collection (raw JSON editor)

**Comment by leplatrem** [comment]
@n1k0 , fixed along with #116?

**Comment by n1k0** [comment]
I do think so!
