### ISSUE TITLE
Only expose buttons for actions the user is allowed to perform

### ISSUE THREAD

**Issue by n1k0** [Kinto/kinto-admin#86]
For example, it makes no sense to render a _Create collection_ button to people not allowed to do so in a given bucket.

Alternatively to hiding action buttons entirely, we could mark them as disabled, and/or add a _lock_ icon next to their label. Thoughts?

Note: This will need https://github.com/Kinto/kinto/issues/600#issuecomment-221537148 
#### Todo
- [x] Hide Add/Bulk add buttons if we don't have the permission to create records in a collection (#135)
- [ ] Hide Create collection sidebar menu entry if we don't have the permission to create collections in a listed bucket
- [x] Hide Create bucket button if no permission to do so (refs #401)

**Comment by n1k0** [comment]
As per discussion with Natouille, it seems the safe option is to hide action buttons users are not allowed to operate.

**Comment by n1k0** [comment]
Partially addressed in #135.
